function lgnctxfigaddline(h0,testname,initrangestr,teststr,xoffset,yoffset)

h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','genercallback', ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[xoffset-18+668-100 yoffset 16 17], ...
	'Style','checkbox', ...
	'Tag',[teststr 'CB']);
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',9, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[xoffset yoffset 114 19], ...
	'String',testname, ...
	'Style','text', ...
	'Tag','StaticText11');
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','genercallback', ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[xoffset-18+383-70 yoffset 62 18], ...
	'String','Run', ...
	'Tag',[teststr 'RunBt']);
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','genercallback', ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[xoffset-18+560-75 yoffset 76 20], ...
	'String','Analyze', ...
	'Tag',['Analyze' teststr 'Bt']);
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[xoffset-18+451-70 yoffset-2 97 20], ...
	'Style','edit', ...
	'Tag',[teststr 'TestEdit']);
h1 = uicontrol('Parent',h0, ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',9, ...
	'ListboxTop',0, ...
	'Position',[xoffset-18+140 yoffset 166 20], ...
	'Style','edit', 'String',initrangestr,...
	'Tag',[teststr 'RangeEdit']);
