function assoclist=lgnassociatelist(testname),

%  lgnassociatelist - list of associates for lgn data analysis
%
%  asclist = lgnassociatelist(testname), cell list

switch(testname),
case 'OT Analysis',
		assoclist = {'OT Response Curve F1','OT Response Curve F0','OT Pref',...
			'OT Circular variance','OT Tuning width','OT Direction index',...
			'OT Spontaneous rate','OT Orientation index',...
			'OT Carandini params F0',...
			'OT Carandini Fit sp','OT Carandini Fit'};
case 'OTVM Analysis',
		assoclist = {'OTVM F1 Response Curve','OTVM F0 Response Curve',...
			'OTVM Max drifting grating voltage',...
			'OTVM Pref',...
			'OTVM Circular variance','OTVM Tuning width',...
			'OTVM Direction index','OTVM Orientation index',...
			'OTVM Spontaneous rate','OTVM Carandini Fit',...
			'OTVM Carandini Fit sp'};
case 'Intrinsic Firing Properties',
		assoclist = {'IT firing rate','IT burster','IT adaptation',...
			'IT interspikeintervals','IT early spikes','IT late spikes',...
			'IT ISI variability','IT burst fraction'};
case 'all',
		assoclist = {};
		testlist = {'OT Analysis'};
		for i=1:length(testlist),
			assoclist = cat(2,assoclist,lgnassociatelist(testlist{i}));
		end;
end;

