function svnrsafig(ds,stackname,img)

pathname = getpathname(ds);
if 0,
plototdirstack(ds,stackname,'rotate',90,'otgray',0,'ot_assoc','OT Fit Pref 2 Peak',...
	'dirthresh',0.5,'dir_assoc','OT Direction index 2 Peak','otdirgreenblue',1);

end;

%img = previewprairieview([pathname filesep 't00007'],30,1,1);

yvalues = 10:0.25:20;

plototystack(ds,stackname,'rotate',90,'y_assoc','POS Fit Pref',...
	'pthreshold_assoc','POS varies p','yvalues',yvalues,...
	'imagesize',[512 512], ...%[pathname filesep 't00007'],...
	'yfunc',...
	'getfield(findassociate(cells{i},''POS Fit Pref'','''',''''),''data'')/18',...
	'scalebarticks',1:8:length(yvalues));
	%'imagesize',[512 512], ... %[pathname filesep 't00007'],...
