function [dirtestnamelist, velocitytestnamelist, scrambledtestnamelist,opticalsurfacetestnamelist] = vhdirectiontrainingtypes(addtest)
% VHDIRECTIONTRAININGTYPES The direction training directory associate types
%
%  [DIRTESTNAMELIST,VELOCITYTESTNAMELIST, SCRAMBLEDTESTNAMELIST,...]=...
%     [OPTICALSURFACETESTNAMELIST, VHDIRECTIONTRAININGTYPES];
% 
%  This function returns the the tags that can be used for
%  T directories for the training experiments.
%
%  If one uses a nonzero input argument, then the string ' test' is appended to all
%  the names.
% 
%
%dirtestnamelist = {'PreDir1Hz','PostDir1Hz','PreDir2Hz','PostDir2Hz','PreDir4Hz','PostDir4Hz',...
%                'PreDir8Hz','PostDir8Hz',...
%                'Dir1Hz1','Dir1Hz2','Dir1Hz3','Dir1Hz4','Dir1Hz5','Dir1Hz6','Dir1Hz7','Dir1Hz8',...
%                'Dir2Hz1','Dir2Hz2','Dir2Hz3','Dir2Hz4','Dir2Hz5','Dir2Hz6','Dir2Hz7','Dir2Hz8',...
%                'Dir4Hz1','Dir4Hz2','Dir4Hz3','Dir4Hz4','Dir4Hz5','Dir4Hz6','Dir4Hz7','Dir4Hz8',...
%                'Dir8Hz1','Dir8Hz2','Dir8Hz3','Dir8Hz4','Dir8Hz5','Dir8Hz6','Dir8Hz7','Dir8Hz8'};
%                  (now also includes opticalsurfacetestnamelist items that are analyzed by angle)
%
%velocitytestnamelist = {'PreVelocity','PostVelocity','Velocity1','Velocity2','Velocity3','Velocity4',...
%                        'TF1','TF2','PreTF','PostTF','TF3','TF4','TFPref1','TFPref2','TFPref3','TFPref4',...
%                         'TFNull1','TFNull2','TFNull3','TFNull4','PreTFPref','PostTFPref','PreTFNull','PostTFNull'};
%                  (now also includes opticalsurfacetestnamelist items that are analyzed by temporal frequency)
%
%scrambledtestnamelist = {'PreBScrambled1Hz','PreBScrambled2Hz','PreBScrambled4Hz','PreBScrambled8Hz',...
%                        'PostBScrambled1Hz','PostBScrambled2Hz','PostBScrambled4Hz','PostBScrambled8Hz',...
%                        'BScrambled1Hz1','BScrambled1Hz2','BScrambled1Hz3','BScrambled1Hz4','BScrambled1Hz5',...
%                        'BScrambled2Hz1','BScrambled2Hz2','BScrambled2Hz3','BScrambled2Hz4','BScrambled2Hz5',...
%                        'BScrambled4Hz1','BScrambled4Hz2','BScrambled4Hz3','BScrambled4Hz4','BScrambled4Hz5',...
%                        'BScrambled8Hz1','BScrambled8Hz2','BScrambled8Hz3','BScrambled8Hz4','BScrambled8Hz5',...
%                        'PreSScrambled1Hz','PreSScrambled2Hz','PreSScrambled4Hz','PreSScrambled8Hz',...
%                        'PostSScrambled1Hz','PostSScrambled2Hz','PostSScrambled4Hz','PostSScrambled8Hz',...
%                        'SScrambled1Hz1','SScrambled1Hz2','SScrambled1Hz3','SScrambled1Hz4','SScrambled1Hz5',...
%                        'SScrambled2Hz1','SScrambled2Hz2','SScrambled2Hz3','SScrambled2Hz4','SScrambled2Hz5',...
%                        'SScrambled4Hz1','SScrambled4Hz2','SScrambled4Hz3','SScrambled4Hz4','SScrambled4Hz5',...
%                        'SScrambled8Hz1','SScrambled8Hz2','SScrambled8Hz3','SScrambled8Hz4','SScrambled8Hz5'};
%
%opticalsurfacetestnamelist = {'PreOPDir1Hz','PostOPDir1Hz','PreOPDir2Hz','PostOPDir2Hz','PreOPDir4Hz','PostOPDir4Hz',...
%                'PreOPDir8Hz','PostOPDir8Hz',...
%                'DirOP1Hz1','DirOP1Hz2','DirOP1Hz3','DirOP1Hz4','DirOP1Hz5','DirOP1Hz6','DirOP1Hz7','DirOP1Hz8',...
%                'DirOP2Hz1','DirOP2Hz2','DirOP2Hz3','DirOP2Hz4','DirOP2Hz5','DirOP2Hz6','DirOP2Hz7','DirOP2Hz8',...
%                'DirOP4Hz1','DirOP4Hz2','DirOP4Hz3','DirOP4Hz4','DirOP4Hz5','DirOP4Hz6','DirOP4Hz7','DirOP4Hz8',...
%                'DirOP8Hz1','DirOP8Hz2','DirOP8Hz3','DirOP8Hz4','DirOP8Hz5','DirOP8Hz6','DirOP8Hz7','DirOP8Hz8',...
%                'PreOPVelocity','PostOPVelocity','VelocityOP1','VelocityOP2','VelocityOP3','VelocityOP4',...
%                 'TFOP1','TFOP2','PreOPTF','PostOPTF','TFOP3','TFOP4','TFPrefOP1','TFPrefOP2','TFPrefOP3','TFPrefOP4',...
%                 'TFOPNull1','TFOPNull2','TFOPNull3','TFOPNull4','PreTFPrefOP','PostTFPrefOP','PreTFNullOP','PostTFNullOP',...
%                'SFOP1Hz1','SFOP1Hz2','SFOP1Hz3','SFOP1Hz4','SFOP1Hz5','SFOP1Hz6','SFOP1Hz7','SFOP1Hz8',...
%                'SFOP2Hz1','SFOP2Hz2','SFOP2Hz3','SFOP2Hz4','SFOP2Hz5','SFOP2Hz6','SFOP2Hz7','SFOP2Hz8',...
%                'SFOP4Hz1','SFOP4Hz2','SFOP4Hz3','SFOP4Hz4','SFOP4Hz5','SFOP4Hz6','SFOP4Hz7','SFOP4Hz8',...
%                'SFOP8Hz1','SFOP8Hz2','SFOP8Hz3','SFOP8Hz4','SFOP8Hz5','SFOP8Hz6','SFOP8Hz7','SFOP8Hz8'}
%
%

dirtestnamelist = {'PreDir1Hz','PostDir1Hz','PreDir2Hz','PostDir2Hz','PreDir4Hz','PostDir4Hz',...
                'PreDir8Hz','PostDir8Hz',...
                'Dir1Hz1','Dir1Hz2','Dir1Hz3','Dir1Hz4','Dir1Hz5','Dir1Hz6','Dir1Hz7','Dir1Hz8',...
                'Dir2Hz1','Dir2Hz2','Dir2Hz3','Dir2Hz4','Dir2Hz5','Dir2Hz6','Dir2Hz7','Dir2Hz8',...
                'Dir4Hz1','Dir4Hz2','Dir4Hz3','Dir4Hz4','Dir4Hz5','Dir4Hz6','Dir4Hz7','Dir4Hz8',...
                'Dir8Hz1','Dir8Hz2','Dir8Hz3','Dir8Hz4','Dir8Hz5','Dir8Hz6','Dir8Hz7','Dir8Hz8',...
		'PreOPDir1Hz','PostOPDir1Hz','PreOPDir2Hz','PostOPDir2Hz','PreOPDir4Hz','PostOPDir4Hz',...
                'PreOPDir8Hz','PostOPDir8Hz',...
                'DirOP1Hz1','DirOP1Hz2','DirOP1Hz3','DirOP1Hz4','DirOP1Hz5','DirOP1Hz6','DirOP1Hz7','DirOP1Hz8',...
                'DirOP2Hz1','DirOP2Hz2','DirOP2Hz3','DirOP2Hz4','DirOP2Hz5','DirOP2Hz6','DirOP2Hz7','DirOP2Hz8',...
                'DirOP4Hz1','DirOP4Hz2','DirOP4Hz3','DirOP4Hz4','DirOP4Hz5','DirOP4Hz6','DirOP4Hz7','DirOP4Hz8',...
                'DirOP8Hz1','DirOP8Hz2','DirOP8Hz3','DirOP8Hz4','DirOP8Hz5','DirOP8Hz6','DirOP8Hz7','DirOP8Hz8'};

velocitytestnamelist = {'PreVelocity','PostVelocity','Velocity1','Velocity2','Velocity3','Velocity4',...
                        'TF1','TF2','PreTF','PostTF','TF3','TF4','TFPref1','TFPref2','TFPref3','TFPref4',...
                         'TFNull1','TFNull2','TFNull3','TFNull4','PreTFPref','PostTFPref','PreTFNull','PostTFNull',...
			'PreOPVelocity','PostOPVelocity','VelocityOP1','VelocityOP2','VelocityOP3','VelocityOP4',...
			'TFOP1','TFOP2','PreOPTF','PostOPTF','TFOP3','TFOP4','TFPrefOP1','TFPrefOP2','TFPrefOP3','TFPrefOP4',...
			'TFOPNull1','TFOPNull2','TFOPNull3','TFOPNull4','PreTFPrefOP','PostTFPrefOP','PreTFNullOP','PostTFNullOP'};

scrambledtestnamelist = {'PreBScrambled1Hz','PreBScrambled2Hz','PreBScrambled4Hz','PreBScrambled8Hz',...
                        'PostBScrambled1Hz','PostBScrambled2Hz','PostBScrambled4Hz','PostBScrambled8Hz',...
                        'BScrambled1Hz1','BScrambled1Hz2','BScrambled1Hz3','BScrambled1Hz4','BScrambled1Hz5',...
                        'BScrambled2Hz1','BScrambled2Hz2','BScrambled2Hz3','BScrambled2Hz4','BScrambled2Hz5',...
                        'BScrambled4Hz1','BScrambled4Hz2','BScrambled4Hz3','BScrambled4Hz4','BScrambled4Hz5',...
                        'BScrambled8Hz1','BScrambled8Hz2','BScrambled8Hz3','BScrambled8Hz4','BScrambled8Hz5',...
 			'PreSScrambled1Hz','PreSScrambled2Hz','PreSScrambled4Hz','PreSScrambled8Hz',...
                        'PostSScrambled1Hz','PostSScrambled2Hz','PostSScrambled4Hz','PostSScrambled8Hz',...
                        'SScrambled1Hz1','SScrambled1Hz2','SScrambled1Hz3','SScrambled1Hz4','SScrambled1Hz5',...
                        'SScrambled2Hz1','SScrambled2Hz2','SScrambled2Hz3','SScrambled2Hz4','SScrambled2Hz5',...
                        'SScrambled4Hz1','SScrambled4Hz2','SScrambled4Hz3','SScrambled4Hz4','SScrambled4Hz5',...
                        'SScrambled8Hz1','SScrambled8Hz2','SScrambled8Hz3','SScrambled8Hz4','SScrambled8Hz5'};

opticalsurfacetestnamelist = {'PreOPDir1Hz','PostOPDir1Hz','PreOPDir2Hz','PostOPDir2Hz','PreOPDir4Hz','PostOPDir4Hz',...
                'PreOPDir8Hz','PostOPDir8Hz',...
                'DirOP1Hz1','DirOP1Hz2','DirOP1Hz3','DirOP1Hz4','DirOP1Hz5','DirOP1Hz6','DirOP1Hz7','DirOP1Hz8',...
                'DirOP2Hz1','DirOP2Hz2','DirOP2Hz3','DirOP2Hz4','DirOP2Hz5','DirOP2Hz6','DirOP2Hz7','DirOP2Hz8',...
                'DirOP4Hz1','DirOP4Hz2','DirOP4Hz3','DirOP4Hz4','DirOP4Hz5','DirOP4Hz6','DirOP4Hz7','DirOP4Hz8',...
                'DirOP8Hz1','DirOP8Hz2','DirOP8Hz3','DirOP8Hz4','DirOP8Hz5','DirOP8Hz6','DirOP8Hz7','DirOP8Hz8',...
                'PreOPVelocity','PostOPVelocity','VelocityOP1','VelocityOP2','VelocityOP3','VelocityOP4',...
                 'TFOP1','TFOP2','PreOPTF','PostOPTF','TFOP3','TFOP4','TFPrefOP1','TFPrefOP2','TFPrefOP3','TFPrefOP4',...
                 'TFOPNull1','TFOPNull2','TFOPNull3','TFOPNull4','PreTFPrefOP','PostTFPrefOP','PreTFNullOP','PostTFNullOP',...
                'PreDir1Hz','PostDir1Hz','PreDir2Hz','PostDir2Hz','PreDir4Hz','PostDir4Hz',...
                'PreDir8Hz','PostDir8Hz',...
                'SFOP1Hz1','SFOP1Hz2','SFOP1Hz3','SFOP1Hz4','SFOP1Hz5','SFOP1Hz6','SFOP1Hz7','SFOP1Hz8',...
                'SFOP2Hz1','SFOP2Hz2','SFOP2Hz3','SFOP2Hz4','SFOP2Hz5','SFOP2Hz6','SFOP2Hz7','SFOP2Hz8',...
                'SFOP4Hz1','SFOP4Hz2','SFOP4Hz3','SFOP4Hz4','SFOP4Hz5','SFOP4Hz6','SFOP4Hz7','SFOP4Hz8',...
                'SFOP8Hz1','SFOP8Hz2','SFOP8Hz3','SFOP8Hz4','SFOP8Hz5','SFOP8Hz6','SFOP8Hz7','SFOP8Hz8'};

if nargin>0,
	if addtest~=0,
		for i=1:length(dirtestnamelist),
			dirtestnamelist{i} = cat(2,dirtestnamelist{i},' test');
		end;
		for i=1:length(velocitytestnamelist),
			velocitytestnamelist{i} = cat(2,velocitytestnamelist{i},' test');
		end;
		for i=1:length(scrambledtestnamelist),
			scrambledtestnamelist{i} = cat(2,scrambledtestnamelist{i},' test');
		end;
		for i=1:length(opticalsurfacetestnamelist),
			opticalsurfacetestnamelist{i} = cat(2,opticalsurfacetestnamelist{i},' test');
		end;
	end;
end;
